services:
  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    image: prismahardiajiriyantoko/test-image:latest
    container_name: moodle
    restart: unless-stopped
    environment:
      - MOODLE_DATABASE_TYPE=pgsql
      - MOODLE_DATABASE_HOST=postgres
      - MOODLE_DATABASE_PORT_NUMBER=5432
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodlepassword
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=adminpassword
      - MOODLE_EMAIL=admin@example.com
      - MOODLE_SITE_NAME=My Moodle
      - MOODLE_SKIP_BOOTSTRAP=no
      - ALLOW_EMPTY_PASSWORD=no
      - MOODLE_REDIS_HOST=redis
      - MOODLE_REDIS_PORT=6379
      - MOODLE_REDIS_PASSWORD=redispassword  
    ports:
      - "6060:8080"
      - "6061:8081"
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      postgres:
        condition: service_healthy  
      redis:
        condition: service_started
    networks:
      - app-moodle
    healthcheck:  
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgrespassword
      - POSTGRESQL_USER=moodle  
      - POSTGRESQL_PASSWORD=moodlepassword
      - POSTGRESQL_DATABASE=moodle
      - ALLOW_EMPTY_PASSWORD=no  
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - app-moodle
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U moodle -d moodle"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=redispassword  
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - redis_data:/bitnami/redis
    networks:
      - app-moodle
    healthcheck:  
      test: ["CMD", "redis-cli", "--pass", "redispassword", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  moodle_data:
  moodledata_data:
  postgres_data:
  redis_data:

networks:
  app-moodle:
    driver: bridge
